### ISSUE TITLE
[Emissions] Wrong label "carbon_emission_carrier" in models with only one carrier

### ISSUE THREAD

**Issue by fradmm** [ZEN-universe/ZEN-explorer#14] opened 2024-08-27 15:16 UTC
Wrong label "carbon_emission_carrier" in models with only one carrier. 

Should be "natural_gas" in 15_multiple_output_carriers_conversion_tech.
![image](https://github.com/user-attachments/assets/d546bff4-8634-4acb-bca6-b1a24d5a8e83)

Same in 12_myopic_foresight, 13_brown_field, and in all models with a single carrier responsible for emissions.

**Comment by jacob-mannhardt** [comment] 2024-09-30 15:34
closed because duplicate of #35

**Closed** 2024-09-30 15:34 UTC
